# Generated by Django 2.1.5 on 2019-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
